# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "medical_warehouse"
version: "1.0.0"

# This setting configures which "profile" dbt uses for this project.
profile: "medical_warehouse"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
    medical_warehouse:
        # Staging models - cleaned and typed raw data
        staging:
            +materialized: view
            +schema: staging

        # Marts - dimensional models for analytics
        marts:
            +materialized: table
            +schema: marts
