medical_warehouse:
    target: dev
    outputs:
        dev:
            type: postgres
            host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
            port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
            user: "{{ env_var('POSTGRES_USER', 'warehouse_user') }}"
            password: "{{ env_var('POSTGRES_PASSWORD', '') }}"
            dbname: "{{ env_var('POSTGRES_DB', 'medical_warehouse') }}"
            schema: staging
            threads: 4
            keepalives_idle: 0

        prod:
            type: postgres
            host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
            port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
            user: "{{ env_var('POSTGRES_USER', 'warehouse_user') }}"
            password: "{{ env_var('POSTGRES_PASSWORD', '') }}"
            dbname: "{{ env_var('POSTGRES_DB', 'medical_warehouse') }}"
            schema: marts
            threads: 4
            keepalives_idle: 0
